### ISSUE TITLE
Response object returns as None on POST

### ISSUE THREAD

**Issue by herrymon** [herrymon/pykaboo#1]
Traceback (most recent call last):
File "pyka.py", line 55, in **call** return self.app(environ, start_response) 
File "pyka.py", line 360, in **call** response_echo.append(resp.show(app_method(), booger)) 
File "pyka.py", line 156, in show str_response = ''.join(response) 
TypeError: sequence item 0: expected string, NoneType foun

**Comment by herrymon** [comment]
Error is not in Response object, but on redirect. There is no Response object because my sample app redirects after a POST. Changed app to show POST values instead of redirecting. POST values are displayed.
